language: java
jdk:
- openjdk7
- oraclejdk7
- oraclejdk8
os:
  - linux
env:
  matrix:
    - NEO_VERSION=2.0.3
    - NEO_VERSION=2.0.5
    - NEO_VERSION=2.1.8
    - NEO_VERSION=2.2.5
      EXTRA_PROFILES=-Pwith-neo4j-io
script: "mvn -T4 clean test -Dneo4j.version=${NEO_VERSION} ${EXTRA_PROFILES}"
after_success:
  - mvn clean test jacoco:report coveralls:report
