sudo: false
cache:
  directories:
    - $HOME/.m2
language: java
install: true
jdk:
- openjdk7
- oraclejdk7
- oraclejdk8
os:
  - linux
env:
  matrix:
    - NEO_VERSION=2.0.3
    - NEO_VERSION=2.0.5
    - NEO_VERSION=2.1.8
    - NEO_VERSION=2.2.7
      EXTRA_PROFILES=-Pwith-neo4j-io
    - NEO_VERSION=2.3.1
      EXTRA_PROFILES=-Pwith-neo4j-io
script: "mvn -T4 clean test -Dneo4j.version=${NEO_VERSION} ${EXTRA_PROFILES}"
after_success:
  - mvn clean test jacoco:report coveralls:report
