version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "daily" # live not supported yet for java/mvn
    default_reviewers:
      - "fbiville"
    target_branch: "2.x"
    ignored_updates:
      - match:
          dependency_name: "org.neo4j:neo4j*"
      - match:
          dependency_name: "org.springframework*"
      - match: # only 2.x works
          dependency_name: "org.assertj*"
      - match: # only 2.x works
          dependency_name: "org.mockito*"
      - match: # 21+ requires JDK 8+
          dependency_name: "com.google.guava*"
